changelog:
  exclude:
    labels:
      - ignore for release
      - wontfix
      - invalid
      - duplicate
  categories:
    - title: New Features ✨
      labels:
        - new feature
    - title: Improvements 🛠
      labels:
        - improvement
    - title: Bug Fixes 🐛
      labels:
        - bug
    - title: Other Changes 📚
      labels:
        - "*"
